"""TODO"""

PACE_SHORTNAMES = [
    # Level 1
    "PACE_HARP2_L1B_SCI",
    "PACE_HARP2_L1C_SCI",
    "PACE_OCI_L1B_SCI",
    "PACE_OCI_L1C_SCI",
    "PACE_SPEXONE_L1A_SCI",
    "PACE_SPEXONE_L1B_SCI",
    "PACE_SPEXONE_L1C_SCI",
    # Level 2
    "PACE_HARP2_L2_CLOUD_GPC",
    "PACE_HARP2_L2_CLOUD_GPC_NRT",
    "PACE_HARP2_L2_MAPOL_OCEAN",
    "PACE_HARP2_L2_MAPOL_OCEAN_NRT",
    "PACE_OCI_L2_AER_UAA",
    "PACE_OCI_L2_AER_UAA_NRT",
    "PACE_OCI_L2_AOP",
    "PACE_OCI_L2_AOP_NRT",
    "PACE_OCI_L2_BGC",
    "PACE_OCI_L2_BGC_NRT",
    "PACE_OCI_L2_CLOUD",
    "PACE_OCI_L2_CLOUD_MASK",
    "PACE_OCI_L2_CLOUD_MASK_NRT",
    "PACE_OCI_L2_CLOUD_NRT",
    "PACE_OCI_L2_IOP",
    "PACE_OCI_L2_IOP_NRT",
    "PACE_OCI_L2_LANDVI",
    "PACE_OCI_L2_LANDVI_NRT",
    "PACE_OCI_L2_PAR",
    "PACE_OCI_L2_PAR_NRT",
    "PACE_OCI_L2_SFREFL",
    "PACE_OCI_L2_SFREFL_NRT",
    "PACE_OCI_L2_UVAI_UAA",
    "PACE_OCI_L2_UVAI_UAA_NRT",
    "PACE_SPEXONE_L2_AER_RTAPLAND",
    "PACE_SPEXONE_L2_AER_RTAPLAND_NRT",
    "PACE_SPEXONE_L2_AER_RTAPOCEAN",
    "PACE_SPEXONE_L2_AER_RTAPOCEAN_NRT",
    "PACE_SPEXONE_L2_MAPOL_OCEAN",
    "PACE_SPEXONE_L2_MAPOL_OCEAN_NRT",
]

EARTHCARE_SHORTNAMES = [
    # Level 1
    "ATL_NOM_1B",
    "AUX_JSG_1D",
    "AUX_MET_1D",
    "BBR_NOM_1B",
    "BBR_SNG_1B",
    "CPR_NOM_1B",
    "MSI_NOM_1B",
    "MSI_RGR_1C",
    # Level 2
    "AC__TC__2B",
    "AM__ACD_2B",
    "AM__CTH_2B",
    "ATL_AER_2A",
    "ATL_ALD_2A",
    "ATL_CTH_2A",
    "ATL_EBD_2A",
    "ATL_FM__2A",
    "ATL_ICE_2A",
    "ATL_TC__2A",
    "BM__RAD_2B",
    "CPR_CD__2A",
    "CPR_CLD_2A",
    "CPR_FMR_2A",
    "CPR_TC__2A",
    "MSI_AOT_2A",
    "MSI_CM__2A",
    "MSI_COP_2A",
]

PACEPAX_SHORTNAMES = [
    "PACE-PAX_AircraftRemoteSensing_ER2_AirHARP2-MAP_Data",
    "PACE-PAX_AircraftRemoteSensing_ER2_HSRL2_Data",
    "PACE-PAX_AircraftRemoteSensing_ER2_PRISM-PICARD-L1C_Data",
    "PACE-PAX_AircraftRemoteSensing_ER2_RSP_Data",
    "PACE-PAX_AircraftRemoteSensing_ER2_SPEXAIRBORNE_Data",
    "PACE-PAX_Analysis_CIRPAS-TO_Data",
    "PACE-PAX_Analysis_ER2_Data",
    "PACE-PAX_Analysis_ISARA_Data",
    "PACE-PAX_CIRPAS-Facility_AircraftInSitu_CIRPAS-TO_Data",
    "PACE-PAX_Ivanpah-Playa_Data",
    "PACE-PAX_LARGE-Aerosol_AircraftInSitu_CIRPAS-TO_Data",
    "PACE-PAX_LARGE-Aerosol_Marina-Tower_Data",
    "PACE-PAX_LiNeph_AircraftInSitu_CIRPAS-TO_Data",
    "PACE-PAX_MetNav_AircraftInSitu_ER2_Data",
]
